### PR TITLE
Added ShiftLeft Scan

### PR DESCRIPTION
**Pull request by prabhu**
Thanks for this excellent project. This PR adds ShiftLeft Scan, a free open-source security tool. Scan is powered by the excellent checkov for checking Kubernetes projects.

Scan is able to identify 200+ vulnerabilities on this repo.

https://github.com/prabhu/kubernetes-goat/runs/782152706?check_suite_focus=true#step:4:32

I think it will be a fun exercise for beginners to go through the html reports produced by scan to understand the best practices as well as trying out the scenarios as intended.

### CODE REVIEW

**Comment by madhuakula** [comment]
Hey @prabhu 

Awesome. That's looks really great. 

As this is intentionally vulnerable Kubernetes cluster environment. It doesn't make sense to add the Github workflow. But it would be really great to see if you want to contribute the defence scenario of `ShiftLeft` scan in Kubernetes Goat.

I am happy to help with creating scenario :)

Thanks again!

**Comment by madhuakula** [comment]
Also, It would be great if we can add the report at least in the documentation book as well. Let me know if you can make a PR for that.

Thanks

**Comment by madhuakula** [comment]
I have just added a section https://madhuakula.com/kubernetes-goat/reports/ would it be possible to add the ShiftLeft report to the documentation guide?

Thanks @prabhu

**Comment by prabhu** [comment]
You can download them from github actions

https://github.com/prabhu/kubernetes-goat/suites/810201387/artifacts/8832895

**Comment by madhuakula** [comment]
Thanks

**Comment by rskreddy07mca** [comment]
Thanks

**Pull request closed without merging**
